"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    const now = new Date();

    await queryInterface.bulkInsert(
      "Products",
      [
        {
          id: 1,
          userId: 1,
          productName: "Hydrating Cleanser",
          productBrand: "AquaSkin",
          productType: "cleanser",
          productImage: null,
          isVerified: true,
          shelf_life_months: 12,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 2,
          userId: 1,
          productName: "Niacinamide 10% Serum",
          productBrand: "GlowLab",
          productType: "serum",
          productImage: null,
          isVerified: true,
          shelf_life_months: 12,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 3,
          userId: 1,
          productName: "Salicylic Acid Cleanser",
          productBrand: "PurePore",
          productType: "cleanser",
          productImage: null,
          isVerified: true,
          shelf_life_months: 12,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 4,
          userId: 1,
          productName: "Retinol Anti-Aging Serum",
          productBrand: "YouthFix",
          productType: "serum",
          productImage: null,
          isVerified: true,
          shelf_life_months: 6,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 5,
          userId: 1,
          productName: "Benzoyl Peroxide Spot Treatment",
          productBrand: "AcneGuard",
          productType: "serum",
          productImage: null,
          isVerified: true,
          shelf_life_months: 6,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 6,
          userId: 1,
          productName: "Mineral Sunscreen SPF 50",
          productBrand: "SunShield",
          productType: "sunscreen",
          productImage: null,
          isVerified: true,
          shelf_life_months: 12,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 7,
          userId: 1,
          productName: "Deep Moisture Cream",
          productBrand: "SilkySkin",
          productType: "moisturizer",
          productImage: null,
          isVerified: true,
          shelf_life_months: 24,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 8,
          userId: 1,
          productName: "Squalane Facial Oil",
          productBrand: "NatureDrop",
          productType: "serum",
          productImage: null,
          isVerified: true,
          shelf_life_months: 24,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 9,
          userId: 1,
          productName: "Aloe Vera Cooling Gel",
          productBrand: "FreshLeaf",
          productType: "moisturizer",
          productImage: null,
          isVerified: true,
          shelf_life_months: 18,
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 10,
          userId: 1,
          productName: "Ceramide Barrier Repair Cream",
          productBrand: "BarrierFix",
          productType: "moisturizer",
          productImage: null,
          isVerified: true,
          shelf_life_months: 24,
          createdAt: now,
          updatedAt: now,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Products", null, {});
  },
};